### ISSUE TITLE
help from Clare and Audrey

### ISSUE THREAD

**Issue by claremcgillis** [austin-leung/Keys-to-Success#2]
**Recursive Abstraction:** 
You say "there exists one path", but we feel it should say "there exists at least one path" in order to make it clear that there could be multiple paths.
You also say "for an adjacent stepping stone that has not been visited before", but the "for" part is a bit unclear. Maybe try changing it to something along the lines of "starting at an adjacent stepping stone...".

**Base Case:** 
"there are no more possible moves for the explorer to take" can be deleted because there can be a smaller case (being in a wall, which you have also listed).

**Comment by Audrey-S00** [comment]
**Pseudo Code: Recursive Case:**
- it's unclear whether you understand what the next smaller step of the problem is.  Right now, your first bullet seems a little vague in terms of what your code would be doing.
- We aren't trying to solve the maze by evaluating valid moves at each intersection.  The explorer is stepping on each space, whether it is a treasure, wall or stepping stone, regardless of whether it is valid or not.
- There is already a method that checks the validity of the explorer space.

**Comment by lbushra** [comment]
Thank you for the help! I think we have fixed the issues that you guys saw. Please let me know if there are any further errors you see.
